name: 'deployphp/action'
description: 'Greet someone and record the time'
inputs:
  who:
    description: 'who to greet'
    required: true
    default: 'world'
outputs:
  time:
    description: 'time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
