name: 'deployphp/action'
description: 'Deploy with Deployer'
inputs:
  private-key:
    description: 'Private key'
    required: true

runs:
  using: 'node12'
  main: 'index.js'
branding:
  color: blue
  icon: server
